#!/bin/bash
#
# Convert SQL batch file obtained from hex-ecs to a plain column data file.
#
# Usage
#
#   tabulate tmat.sql
#

if [ ! -f "$1" ]
then
    echo
    echo "Usage:"
    echo
    echo "  tabulate tmat.sql"
    echo
else
    grep 'INSERT' $1 | sed -e 's/\(.*(\)\(.*\)\().*\)/\2/g' | awk -v FS=',' '
    {
        ni = $1; li = $2; mi = $3;
        nf = $4; lf = $5; mf = $6;
        L = $7; S = $8; E = $9; ell = $10;
        ReT = $11; ImT = $12;
        
        split("spdfghijklmnopqrstuvwxyz", chars, "");
        
        if (mi <= mf)
        {
            printf("%d%c(%d) ",ni,chars[li+1],mi);
            printf("%d%c(%d) ",nf,chars[lf+1],mf);
            printf("%g %d %d %d %g %g\n",E,L,S,ell,ReT,ImT);
        }
    }
    ' | sed 's/\./,/g'
fi
