INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(CLN_INCLUDE_DIR cln/cln.h PATHS ${CLN_INCLUDE_DIRS})
FIND_LIBRARY(CLN_LIBRARY cln ${CLN_LIBRARIES})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CLN REQUIRED_VARS CLN_LIBRARY CLN_INCLUDE_DIR)
