INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(GINAC_INCLUDE_DIR ginac/ginac.h PATHS ${GINAC_INCLUDE_DIRS})
FIND_LIBRARY(GINAC_LIBRARY ginac ${GINAC_LIBRARIES})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GiNaC REQUIRED_VARS GINAC_LIBRARY GINAC_INCLUDE_DIR)
