INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(OPENBLAS_INCLUDE_DIR openblas_config.h ${OPENBLAS_INCLUDE_DIRS})
FIND_LIBRARY(OPENBLAS_LIBRARY NAMES openblas ${OPENBLAS_NAMES} PATHS ${OPENBLAS_LIBRARIES})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenBLAS REQUIRED_VARS OPENBLAS_LIBRARY)

IF(OPENBLAS_FOUND)

    SET(BLAS_FOUND TRUE)
    SET(BLAS_LIBRARIES ${OPENBLAS_LIBRARY})
    SET(BLAS_INCLUDE_DIR ${OPENBLAS_INCLUDE_DIR})
    
    SET(LAPACK_FOUND TRUE)
    SET(LAPACK_LIBRARIES ${OPENBLAS_LIBRARY})
    SET(LAPACK_INCLUDE_DIR ${OPENBLAS_INCLUDE_DIR})
    
ENDIF(OPENBLAS_FOUND)
