INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(GSL_INCLUDE_DIR gsl/gsl_sf.h ${GSL_INCLUDE_DIRS})
FIND_LIBRARY(GSL_LIBRARY NAMES gsl ${GSL_NAMES} PATHS ${GSL_LIBRARIES})
FIND_LIBRARY(GSLCBLAS_LIBRARY NAMES gslcblas ${GSLCBLAS_NAMES} PATHS ${GSL_LIBRARIES})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GSL REQUIRED_VARS GSL_LIBRARY GSL_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GSLCBLAS REQUIRED_VARS GSLCBLAS_LIBRARY)
