INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(GSL_INCLUDE_DIR gsl_sf.h ${GSL_INCLUDE_DIRS} /usr/include/gsl)
FIND_LIBRARY(GSL_LIBRARY gsl ${GSL_LIBRARIES})
FIND_LIBRARY(GSLCBLAS_LIBRARY gslcblas ${GSL_LIBRARIES})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GSL REQUIRED_VARS GSL_LIBRARY GSL_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GSLCBLAS REQUIRED_VARS GSLCBLAS_LIBRARY)
