INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(METIS_INCLUDE_DIR metis.h PATHS ${METIS_INCLUDE_DIRS} /usr/include/suitesparse /usr/include/metis /usr/local/include/metis)
FIND_LIBRARY(METIS_LIBRARY metis ${METIS_LIBRARIES})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(METIS REQUIRED_VARS METIS_LIBRARY METIS_INCLUDE_DIR)
