INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(AMD_INCLUDE_DIR amd.h PATHS ${AMD_INCLUDE_DIRS} /usr/local/include/suitesparse /usr/include/suitesparse)
FIND_LIBRARY(AMD_LIBRARY amd ${AMD_LIBRARIES})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AMD REQUIRED_VARS AMD_LIBRARY AMD_INCLUDE_DIR)

FIND_PATH(CAMD_INCLUDE_DIR camd.h PATHS ${CAMD_INCLUDE_DIRS} /usr/local/include/suitesparse /usr/include/suitesparse)
FIND_LIBRARY(CAMD_LIBRARY camd ${CAMD_LIBRARIES})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CAMD REQUIRED_VARS CAMD_LIBRARY CAMD_INCLUDE_DIR)

FIND_PATH(COLAMD_INCLUDE_DIR colamd.h PATHS ${COLAMD_INCLUDE_DIRS} /usr/local/include/suitesparse /usr/include/suitesparse)
FIND_LIBRARY(COLAMD_LIBRARY colamd ${COLAMD_LIBRARIES})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(COLAMD REQUIRED_VARS COLAMD_LIBRARY COLAMD_INCLUDE_DIR)

FIND_PATH(CCOLAMD_INCLUDE_DIR ccolamd.h PATHS ${CCOLAMD_INCLUDE_DIRS} /usr/local/include/suitesparse /usr/include/suitesparse)
FIND_LIBRARY(CCOLAMD_LIBRARY ccolamd ${CCOLAMD_LIBRARIES})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CCOLAMD REQUIRED_VARS CCOLAMD_LIBRARY CCOLAMD_INCLUDE_DIR)

FIND_PATH(CHOLMOD_INCLUDE_DIR cholmod.h PATHS ${CHOLMOD_INCLUDE_DIRS} /usr/local/include/suitesparse /usr/include/suitesparse)
FIND_LIBRARY(CHOLMOD_LIBRARY cholmod ${CHOLMOD_LIBRARIES})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CHOLMOD REQUIRED_VARS CHOLMOD_LIBRARY CHOLMOD_INCLUDE_DIR)

FIND_PATH(UMFPACK_INCLUDE_DIR umfpack.h PATHS ${UMFPACK_INCLUDE_DIRS} /usr/local/include/suitesparse /usr/include/suitesparse)
FIND_LIBRARY(UMFPACK_LIBRARY umfpack ${UMFPACK_LIBRARIES})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UMFPACK REQUIRED_VARS UMFPACK_LIBRARY UMFPACK_INCLUDE_DIR)

FIND_PATH(SUITESPARSE_CONFIG_INCLUDE_DIR SuiteSparse_config.h PATHS ${SUITESPARSE_CONFIG_INCLUDE_DIRS} /usr/local/include/suitesparse /usr/include/suitesparse)
FIND_LIBRARY(SUITESPARSE_CONFIG_LIBRARY suitesparseconfig ${SUITESPARSE_CONFIG_LIBRARIES})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SuiteSparse_config REQUIRED_VARS SUITESPARSE_CONFIG_LIBRARY SUITESPARSE_CONFIG_INCLUDE_DIR)

FIND_PACKAGE(METIS)

IF(UMFPACK_FOUND)

    TRY_COMPILE(UMFPACK_STAND_ALONE "${CMAKE_BINARY_DIR}"
        SOURCES "${CMAKE_CURRENT_LIST_DIR}/TestUMFPACK.c"
        COMPILE_DEFINITIONS "-I${UMFPACK_INCLUDE_DIR}"
        LINK_LIBRARIES "${UMFPACK_LIBRARY}"
    )

    TRY_COMPILE(UMFPACK_WITH_SUITESPARSE "${CMAKE_BINARY_DIR}"
        SOURCES "${CMAKE_CURRENT_LIST_DIR}/TestUMFPACK.c"
        COMPILE_DEFINITIONS "-I${UMFPACK_INCLUDE_DIR}"
        LINK_LIBRARIES ${UMFPACK_LIBRARY} ${AMD_LIBRARY} ${CAMD_LIBRARY} ${COLAMD_LIBRARY} ${CCOLAMD_LIBRARY} ${CHOLMOD_LIBRARY} ${SUITESPARSE_CONFIG_LIBRARY} ${METIS_LIBRARY} m
    )

    IF(UMFPACK_STAND_ALONE)
        MESSAGE("-- UMFPACK is stand-alone (found).")
    ELSEIF(UMFPACK_WITH_SUITESPARSE)
        MESSAGE("-- UMFPACK needds AMD, CAMD, COLAMD, CCOLAMD, CHOLMOD, SuiteSparse_config and METIS (all found).")
    ELSE()
        MESSAGE("-- Cannot link to UMFPACK.")
        SET(UMFPACK_FOUND FALSE)
    ENDIF()

ENDIF(UMFPACK_FOUND)
